[project]
name = "foxhole"
version = "0.0.1"
authors = [
    {name="Gustaf Gren", email="6107181+skogsgren@users.noreply.github.com"},
]
description = "(Semantic) text search for Firefox history"
dependencies = [
    "scikit-learn==1.6.1",
    "numpy==1.26.4",
]

[project.scripts]
foxhole-install = "foxhole.install:install_native_host"

[project.optional-dependencies]
dev = ["pytest", "ir_measures"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["foxhole"]
